require('./bootstrap');
window.vNotify = require('vanilla-notify');
window.dayjs = require('dayjs');
const { left } = require('@popperjs/core');
let AdvancedFormat = require('dayjs/plugin/advancedFormat');
let calendar = require('dayjs/plugin/calendar');
let customParseFormat = require('dayjs/plugin/customParseFormat');
let duration = require('dayjs/plugin/duration');
let isBetween = require('dayjs/plugin/isBetween');
let pluralGetSet = require('dayjs/plugin/pluralGetSet');
let localeData  = require('dayjs/plugin/localeData');
let updateLocale = require('dayjs/plugin/updateLocale');
let localeES = require('dayjs/locale/es');
window.dayjs.extend(AdvancedFormat);
window.dayjs.extend(calendar);
window.dayjs.extend(customParseFormat);
window.dayjs.extend(duration);
window.dayjs.extend(isBetween);
window.dayjs.extend(pluralGetSet);
window.dayjs.extend(localeData);
window.dayjs.extend(updateLocale);
window.dayjs.extend(localeES);